In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import os

In [4]:
ldr = os.listdir('/media/disk1/Data/SpuriousCatDogVer3/')

In [5]:
[i for i in ldr if 'csv' in i]

['metadata_catdog2.csv', 'metadata.csv']

In [6]:
df = pd.read_csv('/media/disk1/Data/SpuriousCatDogVer3/metadata_catdog2.csv')

In [7]:
df

,index,fg_filename,species,y,split,place,place_filename,img_filename
0,0,Abyssinian_1.jpg,Abyssinian,0,train,0,canyon/gsun_000000a90e084bef1674997d879b14a5.jpg,Abyssinian_1_gsun_000000a90e084bef1674997d879b...
1,1,Abyssinian_10.jpg,Abyssinian,0,train,0,canyon/gsun_00002631f4ffd977e8abc8d5b133c069.jpg,Abyssinian_10_gsun_00002631f4ffd977e8abc8d5b13...
2,2,Abyssinian_100.jpg,Abyssinian,0,train,0,canyon/gsun_00067b2e24505cb7d026724039ac3b57.jpg,Abyssinian_100_gsun_00067b2e24505cb7d026724039...
3,3,Abyssinian_101.jpg,Abyssinian,0,train,0,canyon/gsun_00130f6df09e57028f387f3c12a582ef.jpg,Abyssinian_101_gsun_00130f6df09e57028f387f3c12...
4,4,Abyssinian_102.jpg,Abyssinian,0,train,0,canyon/gsun_0013e19bc3c42c0120c21f44758ec153.jpg,Abyssinian_102_gsun_0013e19bc3c42c0120c21f4475...
...,...,...,...,...,...,...,...,...
8863,7360,yorkshire_terrier_72.jpg,yorkshire_terrier,1,test,1,islet/gsun_c79ece34c6697cdea6b4a6977352ed12.jpg,yorkshire_terrier_72_gsun_c79ece34c6697cdea6b4...
8864,7364,yorkshire_terrier_76.jpg,yorkshire_terrier,1,test,1,islet/gsun_c7b93a6affb42232ad77f9c15efe8695.jpg,yorkshire_terrier_76_gsun_c7b93a6affb42232ad77...
8865,7367,yorkshire_terrier_79.jpg,yorkshire_terrier,1,test,1,islet/gsun_c7baba51dcf5f38897c822a4df0051e0.jpg,yorkshire_terrier_79_gsun_c7baba51dcf5f38897c8...
8866,7372,yorkshire_terrier_83.jpg,yorkshire_terrier,1,test,1,islet/gsun_c7baf88893658d9dfb7441c79518d431.jpg,yorkshire_terrier_83_gsun_c7baf88893658d9dfb74...
8867,7376,yorkshire_terrier_87.jpg,yorkshire_terrier,1,test,1,islet/gsun_c7c2c903d6164485088cc04b38adac07.jpg,yorkshire_terrier_87_gsun_c7c2c903d6164485088c...

In [8]:
df2 = pd.read_csv('/media/disk1/Data/SpuriousCatDogVer3/metadata.csv')

In [9]:
df2

                                               filename  split  y  a
0     Abyssinian_1_gsun_000000a90e084bef1674997d879b...      0  0  0
1     Abyssinian_10_gsun_00002631f4ffd977e8abc8d5b13...      0  0  0
2     Abyssinian_100_gsun_00067b2e24505cb7d026724039...      0  0  0
3     Abyssinian_101_gsun_00130f6df09e57028f387f3c12...      0  0  0
4     Abyssinian_102_gsun_0013e19bc3c42c0120c21f4475...      0  0  0
...                                                 ...    ... .. ..
8863  yorkshire_terrier_72_gsun_c79ece34c6697cdea6b4...      2  1  1
8864  yorkshire_terrier_76_gsun_c7b93a6affb42232ad77...      2  1  1
8865  yorkshire_terrier_79_gsun_c7baba51dcf5f38897c8...      2  1  1
8866  yorkshire_terrier_83_gsun_c7baf88893658d9dfb74...      2  1  1
8867  yorkshire_terrier_87_gsun_c7c2c903d6164485088c...      2  1  1

[8868 rows x 4 columns]

In [10]:
df3 = pd.read_csv('/media/disk1/Data/waterbirds/waterbird_complete95_forest2water2/metadata.csv')

In [11]:
df3

,img_id,img_filename,y,split,place,place_filename
0,1,001.Black_footed_Albatross/Black_Footed_Albatr...,1,2,1,/o/ocean/00002178.jpg
1,2,001.Black_footed_Albatross/Black_Footed_Albatr...,1,0,1,/l/lake/natural/00000065.jpg
2,3,001.Black_footed_Albatross/Black_Footed_Albatr...,1,2,0,/b/bamboo_forest/00000131.jpg
3,4,001.Black_footed_Albatross/Black_Footed_Albatr...,1,0,1,/o/ocean/00001268.jpg
4,5,001.Black_footed_Albatross/Black_Footed_Albatr...,1,0,1,/o/ocean/00003147.jpg
...,...,...,...,...,...,...
11783,11784,200.Common_Yellowthroat/Common_Yellowthroat_00...,0,0,0,/f/forest/broadleaf/00001288.jpg
11784,11785,200.Common_Yellowthroat/Common_Yellowthroat_00...,0,2,0,/f/forest/broadleaf/00004142.jpg
11785,11786,200.Common_Yellowthroat/Common_Yellowthroat_00...,0,2,0,/f/forest/broadleaf/00003041.jpg
11786,11787,200.Common_Yellowthroat/Common_Yellowthroat_00...,0,0,0,/b/bamboo_forest/00004628.jpg
11787,11788,200.Common_Yellowthroat/Common_Yellowthroat_00...,0,2,1,/o/ocean/00001069.jpg

In [12]:
df4 = pd.read_csv('/media/disk1/Data/waterbirds/waterbird_complete95_forest2water2/metadata_waterbirds.csv')

In [13]:
df4

          id                                           filename  split  y  a
0          1  001.Black_footed_Albatross/Black_Footed_Albatr...      2  1  1
1          2  001.Black_footed_Albatross/Black_Footed_Albatr...      0  1  1
2          3  001.Black_footed_Albatross/Black_Footed_Albatr...      2  1  0
3          4  001.Black_footed_Albatross/Black_Footed_Albatr...      0  1  1
4          5  001.Black_footed_Albatross/Black_Footed_Albatr...      0  1  1
...      ...                                                ...    ... .. ..
11783  11784  200.Common_Yellowthroat/Common_Yellowthroat_00...      0  0  0
11784  11785  200.Common_Yellowthroat/Common_Yellowthroat_00...      2  0  0
11785  11786  200.Common_Yellowthroat/Common_Yellowthroat_00...      2  0  0
11786  11787  200.Common_Yellowthroat/Common_Yellowthroat_00...      0  0  0
11787  11788  200.Common_Yellowthroat/Common_Yellowthroat_00...      2  0  1

[11788 rows x 5 columns]